name: Compile test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Installing Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installing dependencies
        run: npm install
      - name: Running linter and compile
        run: npm run build