name: Generate docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Node.js v12
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "12"
      - run: |
          git fetch origin main
          git checkout main
      - name: Installing dependencies
        run: npm install
      - name: Generating docs
        run: npm run docs
      - name: Force add docs
        run: git add docs -f
      - name: Configuring user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Commit and push
        run: |
          git commit -m "docs: from ${GITHUB_SHA}" || true
          git push origin main